### ISSUE TITLE
Razorscale, Lua error...

### ISSUE THREAD

**Issue by beldense** [ajseward/DBM-Frostmourne#14]
https://i.imgur.com/hdv0bI9.jpg
https://i.imgur.com/vs8IVj3.jpg

Happens to me on Razorscale, not really sure why...

**Comment by beldense** [comment]
Are you also available in discord somehow? Or maybe create and specific discord for it... ^^

And want to point out another thing about XT002, maybe if your doing it by vod or playing yourself, timers on XT002 seems abit off from Frostmourne version...
I think tantrum cd should be 60 seconds from start and not 50... try that

**Comment by andrew6180** [comment]
The timers were entirely guess work because ulduar was not released on frostmourne. I'll time it based on a vod.

**Comment by andrew6180** [comment]
Neither of those errors have anything to do with dbm. DBM Does not use ace outside of DBM-Profiles, which doesn't use AceEvent.

**Comment by beldense** [comment]
Its really weird because it only happens on razorscale in 25 man and 10 man

**Comment by andrew6180** [comment]
Can't say why but I will say AceEvent 2.0 is extremely old.

**Comment by andrew6180** [comment]
xt was fixed in https://github.com/ajseward/DBM-Frostmourne/commit/eec60794292cb2a4ba3cf4b83e2a04d5c3c65819 so im closing this
