### ISSUE TITLE
Ignis flame jets - no timer? 

### ISSUE THREAD

**Issue by lulwut** [ajseward/DBM-Frostmourne#17]
On 25 ignis (not sure about 10) there was timer for flame jets, I've checked to make sure it was enabled and it was. Haven't confirmed if anyone else has had this issue however.

**Comment by andrew6180** [comment]
Our guild skipped ignis but looking at the code there is no reason for it to not show up. I'll leave this open for now and try and do ignis our next raid to see what the issue is.

**Comment by lulwut** [comment]
I did the raid again, when you pull Ignis right away 3-second timer for flame jets starts to countdown, and thereafter there are no timers for it.

**Comment by andrew6180** [comment]
10 or 25? I just did it on 25 and had timers the entire time.

**Comment by lulwut** [comment]
Weird, 10 and 25, I'll try remember to record my kill when I go next to see.
