### ISSUE TITLE
[Request] Mimiron HC Flames Special Warning

### ISSUE THREAD

**Issue by ghost** [ajseward/DBM-Frostmourne#20]
Hello, would it be possible to add special warning for Flames. Seen it used in different DBM version and its quite nice, https://github.com/Vnm-Kronos/DBM-Angrathar/blob/master/DBM-Ulduar/Mimiron.lua

Gives warning and countdown on Flames in 5 seconds. 

Thanks for all you doing, cheers

**Comment by andrew6180** [comment]
Yeah I'll get on this.

**Comment by ghost** [comment]
Very nice thanks, also on Hard Mode second and third phase flames are delayed. Need some tweaking, Flames occur after the timer exprires, delay is bigger later on in fight.. in third phase flames are like 3-5 secs later.. I wanted to go through timeline in details but for some reason timeline is not working on mimiron ecounter..

**Comment by andrew6180** [comment]
https://www.twitch.tv/videos/690093209 im going off this vod atm, not sure if 10 and 25 timers are different on warmane.

**Comment by ghost** [comment]
Aight, gonna do some pulls today on 10m hc, will try this experimental and report back then.

**Comment by Zidras** [comment]
Took a quick glance on the code. @ajseward could you please recheck if the sound files are in the dbm-core?

**Comment by ghost** [comment]
Sound files are not present, just code change, i downloaded the sound files from link in OP.

**Comment by andrew6180** [comment]
sorry didn't actually add them, they're in now with https://github.com/ajseward/DBM-Frostmourne/commit/b094737bea590155211cd5eced542c9118ed6822

**Comment by ghost** [comment]
Flames timers are  fine now, warning works as well.. P1 to P2 timer is like 5 seconds longer than it should be.

**Comment by andrew6180** [comment]
https://github.com/ajseward/DBM-Frostmourne/commit/a8c467a6615bc070e2b2e775238f4ad691fa9fd7

**Comment by andrew6180** [comment]
It's sounds like this is now working as expected. Open a new issue if there is further problems.
