### ISSUE TITLE
Question regarding phases

### ISSUE THREAD

**Issue by Zidras** [ajseward/DBM-Frostmourne#3]
I noticed on retail dbm that the `local phase` variable is always present with `mod.vb.`. 
But on this version we have been removing that and just adding `self.vb`.
Since after your explanation on details repo, I've been trying to do the same as you, but after going through the icc luas, I had this doubt and I wanted to ask you about it (Didn't know your discord so I couldn't pm you with this, sorry for the wall of text).

**Comment by andrew6180** [comment]
Self is a reference to the table the function is contained in. In almost every case, that means self refers to mod. 

If the function were local then you'd use mod.vb.phase

https://stackoverflow.com/a/17263653/11356926

**Comment by Zidras** [comment]
Let me post an example from dbm classic onyxia, just for some comparison with ours.

- DBM classic (https://github.com/DeadlyBossMods/DBM-Classic/blob/master/DBM-Onyxia/Onyxia.lua#L59-L68):

```
mod.vb.warned_preP2 = false
mod.vb.warned_preP3 = false
mod.vb.phase = 0
--mod.vb.whelpsCount = 0

function mod:OnCombatStart(delay)
	self.vb.phase = 1
	--self.vb.whelpsCount = 0
    self.vb.warned_preP2 = false
	self.vb.warned_preP3 = false
```

where we have the phase defined as `mod.vb.phase` (as well as the other locals) and then `self.vb.phase` throughout the rest of the code.

- DBM-Frostmourne:

```
local warned_preP2 = false
local warned_preP3 = false
function mod:OnCombatStart(delay)
	self.vb.phase = 1
    warned_preP2 = false
	warned_preP3 = false
```

which is "missing" the `mod.vb.phase = 0`

- DBM retail 3.3.5:

```
local warned_preP2 = false
local warned_preP3 = false
local phase = 0
function mod:OnCombatStart(delay)
	phase = 1
    warned_preP2 = false
	warned_preP3 = false
```

just for comparison (no self, no mod, all locals).

______

@ajseward Even with your clarification, if I'd look into DBM-Frostmourne, I still don't understand what are the pros and cons of coding it like so:
```
local warned_preP2 = false
local warned_preP3 = false
mod.vb.phase = 0

function mod:OnCombatStart(delay)
	self.vb.phase = 1
    warned_preP2 = false
	warned_preP3 = false
```

or even changing all the locals:
```
mod.vb.warned_preP2 = false
mod.vb.warned_preP3 = false
mod.vb.phase = 0

function mod:OnCombatStart(delay)
	self.vb.phase = 1
    self.vb.warned_preP2 = false
	self.vb.warned_preP3 = false
```

(PS: Thank you for taking the time to explain this stuff to me and linking documentation.)

**Comment by andrew6180** [comment]
```lua
function mod:OnCombatStart(delay)
    self.vb.phase = 1
end
```
is the same as 
```lua
function mod:OnCombatStart(delay)
    mod.vb.phase = 1
end
```


As for declaring `mod.vb.phase = 0` in the file, my guess is when the entire `vb` table was added, `.phase` is used elsewhere in dbm code, or some other plugin / addon that depends on `.vb.phase`. 

Technically it is wrong to not have mod.vb.phase = 0 in the root of every phased fight, but it's harmless in terms of what it was added for (details backport). 

It just means the first time you enter an area and it says "DBM-xxxx loaded for this area." or whatever the print is, technically mod.vb.phase will return nil when 0 is expected. 

Details handles it being nil so it doesn't matter for that.

Doing a quick search through retail dbm, it's used to reply to whispers with what phase of the fight the player is in.
