### ISSUE TITLE
[Request] Addition of Range Check Radar

### ISSUE THREAD

**Issue by Esstiven** [ajseward/DBM-Frostmourne#7]
So a while back, there were some people that did some work in a DBM fork for Angrathar-Sunwell and they were smart enough to implement this Range Check Radar instead of the conventional Range Check displayed as a list.
![image](https://user-images.githubusercontent.com/50774648/86966809-c030b100-c137-11ea-8dde-f8f1995eb96c.png)
This would put this DBM version over the top from what It already is.
[DBM-Angrathar-master.zip](https://github.com/ajseward/DBM-Frostmourne/files/4893068/DBM-Angrathar-master.zip)
Props to all of you guys,
Keep up the good work the community appreciates it.

**Comment by andrew6180** [comment]
I'll check it out
